# header ------------------------------------------------------------------

# Author: Christine Pu (cjpu@stanford.edu)
# Date Created: June 4, 2023
# Purpose: Combine graphs displaying box and whisker plots of the differences in percentile rankings based on households' PPI scores, DHS scores, and regular expenditures per capita in Ethiopia, Ghana, and Uganda among b20 households:
# Panel A: defined by households' DHS wealth index scores
# Panel B: defined by households' PPI scores
# Panel C: defined by households' regular expenditures per capita
# Inputs: Graphs (boxplot_percent_rankings_diff_b20_dhs, boxplot_percent_rankings_diff_b20_ppi, boxplot_percent_rankings_diff_b20_regexp) generated by diff_rankings_b20_dhs.R, diff_rankings_b20_ppi.R, diff_rankings_b20_regexp.R, respectively
# Outputs: Supplementary Figure 4

# load packages -----------------------------------------------------------

library(tidyverse)
library(dplyr)
library(here)
library(ggpubr)
library(ggthemes)

# source relevant files ---------------------------------------------------

source(here("code", "visualizations", "figS4", "diff_rankings_b20_dhs.R"))
source(here("code", "visualizations", "figS4", "diff_rankings_b20_ppi.R"))
source(here("code", "visualizations", "figS4", "diff_rankings_b20_regexp.R"))

# combine graphs into one figure ------------------------------------------

combine_percent_rankings_b20 <- 
  ggarrange(
    boxplot_percent_rankings_diff_b20_dhs,
    boxplot_percent_rankings_diff_b20_ppi,
    boxplot_percent_rankings_diff_b20_regexp,
    nrow = 1,
    labels = c("A", "B", "C"),
    font.label=list(color="black",size=20)
  )

combine_percent_rankings_b20
